export const DISCOVER_PAGE_SIZE = 24;

export const DISCOVER_FIGURE_AVATAR_SIZE = 64;

export const DISCOVER_CARD_REVEAL_STAGGER_MS = 60;

export const DISCOVER_CARD_REVEAL_MAX_STEPS = 8;

export const DISCOVER_BOOK_COVER_WIDTH = 140;

export const DISCOVER_FIGURE_HERO_AVATAR_SIZE = 224;

export const DISCOVER_BOOK_HERO_COVER_WIDTH = 220;

export const DISCOVER_BIO_TRUNCATE_LENGTH = 140;

export const DISCOVER_FIGURE_BOOKS_PAGE_SIZE = 24;

export const DISCOVER_STATIC_FIGURE_LIMIT = 300;
